# Generated by Django 4.2.8 on 2023-12-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='gave_up',
            field=models.BooleanField(default=False),
        ),
    ]
