# Generated by Django 4.2.7 on 2023-11-17 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_player_score_alter_game_finale_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
