# source $SCRIPTS/.colours.sh

alias HELP="$SCRIPTS/.help.sh"

echo ""
echo " >>> HELP MENU <<< "
echo ""
echo "GIT SHORTCUTS :"
echo ""
echo "    GO   : git optain < repo-url >       : git clone ..."
echo "    GS   : git status                    : git status"
echo "    GP   : git pull                      : git pull"
echo "    GU   : git update                    : git remote update"
echo "    GA   : git add                       : git add * & -u"
echo "    GC   : git commit < message >        : git commit ..."
echo "    GL   : git list                      : git list"
echo "    GG   : git go < dst_branch >         : git switch ..."
echo ""
echo "    GNB  : git new < branch >            : git push origin < src_branch:dst_branch >"
echo "    GDB  : git delete < branch >         : git branch -d <branch>"
echo "    GFT  : git fetch < branch >          : git fetch origin/..."
echo "    GMRG : git merge < src_branch >      : git merge ..."
echo "    GPSH : git push                      : git push"
echo "    GCQP : git quick_push                : ( add, commit and push with comment \"minor\" )"
echo "    GRSET: git reset < branch >          : git reset --hard origin/..."
echo ""
