# Generated by Django 4.2.7 on 2023-11-04 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=60, unique=True)),
                
                ('img_link', models.CharField(max_length=120, unique=False)),
                ('img_vlarg', models.CharField(max_length=120, unique=False)),
                ('img_vmed', models.CharField(max_length=120, unique=False)),
                ('img_vsmall', models.CharField(max_length=120, unique=False)),
                ('img_vmicro', models.CharField(max_length=120, unique=False)),
                
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
