# Generated by Django 4.2.7 on 2023-11-08 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_date_joined_remove_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=128,
                verbose_name="password",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(max_length=60),
        ),
    ]
