# Generated by Django 4.2.7 on 2023-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_last_login_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=120),
        ),
    ]
