# Generated by Django 4.2.6 on 2023-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="img_vlarg",
        ),
        migrations.RemoveField(
            model_name="user",
            name="img_vmed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="img_vmicro",
        ),
        migrations.RemoveField(
            model_name="user",
            name="img_vsmall",
        ),
    ]
