# Generated by Django 4.2.7 on 2023-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='running_game',
            field=models.CharField(default='', max_length=32),
        ),
    ]
