# Generated by Django 4.2.7 on 2023-11-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_running_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='running_game',
        ),
    ]
