# Generated by Django 4.2.7 on 2023-11-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_is_broken_alter_game_ended_at_alter_game_winner'),
        ('users', '0009_remove_user_running_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game'),
        ),
    ]
